name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    -name: clone erofs-utils
     run: git clone https://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git
     
    -name: clone kbd
     run: git clone https://git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git
     
    -name: clone history
     run: git clone https://git.kernel.org/pub/scm/linux/kernel/git/tglx/history.git
     
    - name: clone archive
      run: git clone https://kernel.googlesource.com/pub/scm/linux/kernel/git/nico/archive


    - name: Run make
      run: make
