name: Makefile CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test code
      run: |
        make
        make test

    - name: Deploy to production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: make deploy

