name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and test code
      run: |
        make
        make test

    - name: Deploy to production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: make deploy
